/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class CalculatorTest {
  @Test public void testAddsTwoAndTwo() { //@test identifier is an annotation. JUnit knows now which method to run as tests thanks to annotation.
    Calculator calc = new Calculator();
    assertEquals("2 + 2 should equal 4", Integer.valueOf(4), calc.add(2, 2)); //assert equals = expect() or test()
  }
}