/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args){

    }

    public String getPriceLabel(String item, int price) {
        return "The price for item: " + item + " is " + price;

    }
}
